version: '3.7'

services:
  postgres-user:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="weatherbys-api","test-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - db_data:/data/postgres
    ports:
      - 5432:5432
volumes:
  db_data: {}
